import type { TicketTemplate, TemplateContext, Ticket } from '../../../kernel/types.js';
import { DEPARTMENT_SKILLS } from '../../../kernel/types.js';

export const dryRunTemplate: TicketTemplate = {
  type: 'dry-run',

  generate(_context: TemplateContext): Ticket[] {
    return [
      {
        id: 'DRY-001',
        title: 'Backend: endpoint GET /health + teste automatizado',
        department: 'backend',
        priority: 'high',
        mode: 'sequential',
        repo_paths: ['src/server.js', 'test/health.test.js'],
        constraints: [
          'Sem dependencias externas — usar apenas http nativo do Node.js',
          'Servidor deve escutar em porta configuravel (env PORT ou 3000)',
        ],
        definition_of_done: [
          'GET /health retorna 200 com JSON { status: "ok", timestamp: ISO8601 }',
          'Teste automatizado com node:test passa',
          'Servidor fecha gracefully apos teste',
        ],
        skills_required: [...DEPARTMENT_SKILLS['backend']],
        validation_commands: ['node --test test/health.test.js'],
        outputs: ['src/server.js', 'test/health.test.js'],
        status: 'pending',
        retries: 0,
        error_history: [],
      },
      {
        id: 'DRY-002',
        title: 'Frontend: view HTML que exibe status do /health',
        department: 'frontend',
        priority: 'high',
        mode: 'sequential',
        repo_paths: ['public/index.html', 'test/frontend.test.js'],
        constraints: [
          'HTML puro — sem frameworks',
          'Fetch para /health e exibir status e timestamp',
          'Elemento com id="status" para facilitar teste',
        ],
        definition_of_done: [
          'public/index.html e HTML valido com fetch para /health',
          'Exibe status e timestamp em elementos identificaveis',
          'Teste verifica estrutura do HTML',
        ],
        skills_required: [...DEPARTMENT_SKILLS['frontend']],
        validation_commands: ['node --test test/frontend.test.js'],
        outputs: ['public/index.html', 'test/frontend.test.js'],
        status: 'pending',
        retries: 0,
        error_history: [],
      },
      {
        id: 'DRY-003',
        title: 'Infra: pipeline CI local com lint/test/build',
        department: 'infra-devops',
        priority: 'medium',
        mode: 'parallel',
        repo_paths: ['scripts/ci.sh', '.github/workflows/ci.yml'],
        constraints: [
          'Script bash com set -euo pipefail',
          'Pipeline: lint -> test -> build',
          'Exit code nao-zero se qualquer etapa falhar',
        ],
        definition_of_done: [
          'scripts/ci.sh executavel e funcional',
          '.github/workflows/ci.yml valido',
          'bash scripts/ci.sh executa sem erros',
        ],
        skills_required: [...DEPARTMENT_SKILLS['infra-devops']],
        validation_commands: ['bash scripts/ci.sh'],
        outputs: ['scripts/ci.sh', '.github/workflows/ci.yml'],
        status: 'pending',
        retries: 0,
        error_history: [],
      },
      {
        id: 'DRY-004',
        title: 'Security: script de deteccao de secrets em commits',
        department: 'security',
        priority: 'medium',
        mode: 'parallel',
        repo_paths: ['scripts/secret-scan.sh'],
        constraints: [
          'Detectar: AWS keys, passwords, private keys, GitHub tokens, OpenAI keys, Slack tokens',
          'Retornar 0 em projeto limpo, 1 se encontrar secrets',
          'Scan recursivo em src/, public/, scripts/',
        ],
        definition_of_done: [
          'scripts/secret-scan.sh executavel',
          'Detecta pelo menos 6 padroes de secrets',
          'Retorna 0 em projeto sem secrets',
        ],
        skills_required: [...DEPARTMENT_SKILLS['security']],
        validation_commands: ['bash scripts/secret-scan.sh'],
        outputs: ['scripts/secret-scan.sh'],
        status: 'pending',
        retries: 0,
        error_history: [],
      },
      {
        id: 'DRY-005',
        title: 'QA: validar DoD de todos os tickets + gerar relatorio',
        department: 'qa-verifier',
        priority: 'high',
        mode: 'sequential',
        repo_paths: ['.maestro/reports/dry_run.md'],
        constraints: [
          'Verificar existencia de todos os outputs de DRY-001 a DRY-004',
          'Executar todos os validation_commands',
          'Gerar relatorio em .maestro/reports/dry_run.md',
        ],
        definition_of_done: [
          'Todos os outputs de DRY-001 a DRY-004 existem',
          'Todos os validation_commands passam',
          '.maestro/reports/dry_run.md gerado com veredicto',
        ],
        skills_required: [...DEPARTMENT_SKILLS['qa-verifier']],
        depends_on: ['DRY-001', 'DRY-002', 'DRY-003', 'DRY-004'],
        validation_commands: [
          'test -f src/server.js',
          'test -f public/index.html',
          'test -f scripts/ci.sh',
          'test -f scripts/secret-scan.sh',
        ],
        outputs: ['.maestro/reports/dry_run.md'],
        status: 'pending',
        retries: 0,
        error_history: [],
      },
    ];
  },
};
